/// Pure text normalisation helpers shared by the dictionary engine, the index
/// builder and the import tool. No Flutter imports, so these run anywhere
/// (isolates, CLI tools, tests, web).
library;

/// Lowercases and normalises [raw] for lookups and search: strips apostrophes
/// and curly quotes, replaces punctuation with spaces and collapses
/// whitespace, keeping all letters (Latin and Persian) and digits.
String normalizeText(String raw) {
  return raw
      .toLowerCase()
      .replaceAll(RegExp(r"[\u2018\u2019']"), '')
      .replaceAll(RegExp(r"[^\p{L}\p{N}\s]", unicode: true), ' ')
      .trim()
      .replaceAll(RegExp(r'\s{2,}'), ' ');
}

/// Deterministic, JSON- and filesystem-safe slug of [raw]
/// (e.g. `Good morning` -> `good-morning`). Used as the fallback stable
/// identifier of entries without an explicit `id`.
String slug(String raw) => raw
    .toLowerCase()
    .replaceAll(RegExp(r'\s+'), '-')
    .replaceAll(RegExp(r'[^\p{L}\p{N}-]', unicode: true), '');

/// Deterministic 31-bit polynomial hash (Java `String.hashCode`-style).
/// Unlike `String.hashCode` it is stable across platforms and VM versions, so
/// index buckets generated by the import tool match lookups at runtime.
int headwordHash(String text) {
  var hash = 0;
  for (final unit in text.codeUnits) {
    hash = (hash * 31 + unit) & 0x7fffffff;
  }
  return hash;
}

/// True when [query] looks like a headword (Latin letters, digits, spaces) and
/// therefore can be served by the index's prefix table. Persian (and other
/// non-Latin) queries fall back to a full scan over translations and examples.
bool isHeadwordQuery(String query) =>
    RegExp(r'^[\p{L}\p{N} ]+$', unicode: true).hasMatch(query) &&
    !RegExp(r'[\u0600-\u06FF]').hasMatch(query);
