/// A contextual example produced by the AI tutor: a sentence in the source
/// language plus its gloss in the learner's target language.
class AiExample {
  const AiExample({required this.sentence, required this.translation});

  /// The example sentence in the source (learning) language.
  final String sentence;

  /// The gloss of [sentence] in the target (native) language.
  final String translation;

  bool get isEmpty => sentence.trim().isEmpty && translation.trim().isEmpty;

  Map<String, dynamic> toJson() => {
        'sentence': sentence,
        'translation': translation,
      };

  factory AiExample.fromJson(Map<String, dynamic> json) => AiExample(
        sentence: json['sentence'] as String? ?? '',
        translation: json['translation'] as String? ?? '',
      );
}

/// Structured word details generated by the AI tutor on demand.
///
/// Beyond the plain gloss this carries the phonetic guide (IPA), the part of
/// speech, the grammatical gender of nouns (`der`/`die`/`das` for German) and
/// contextual example sentences with translations — everything a learner needs
/// to master one word. Results are cached locally so repeat lookups are
/// instant and the app stays usable under rate limits or offline.
class AiWordDetails {
  const AiWordDetails({
    required this.word,
    required this.source,
    required this.target,
    this.translation,
    this.phonetic,
    this.partOfSpeech,
    this.gender,
    this.definition,
    this.examples = const [],
    this.alternates = const [],
    this.fromCache = false,
    this.cachedAt,
  });

  /// The queried word in the source language.
  final String word;

  /// ISO 639-1 code of the source language, e.g. `en`, `de`.
  final String source;

  /// ISO 639-1 code of the target (native/explanation) language, e.g. `fa`.
  final String target;

  /// The primary gloss in [target].
  final String? translation;

  /// Pronunciation guide, usually IPA (e.g. `/həˈloʊ/`).
  final String? phonetic;

  /// Part of speech tag when the model returns one.
  final String? partOfSpeech;

  /// Grammatical gender (`der`/`die`/`das`, `el`/`la`, ...) when the source
  /// language genders its nouns.
  final String? gender;

  /// A fuller meaning written in [target].
  final String? definition;

  /// Contextual example sentences, each with its own gloss.
  final List<AiExample> examples;

  /// Other accepted translations.
  final List<String> alternates;

  /// True when served from the local cache rather than the model.
  final bool fromCache;

  /// When the result was cached, if known.
  final DateTime? cachedAt;

  /// True when the response carried nothing usable.
  bool get isEmpty =>
      word.trim().isEmpty || (translation?.trim().isEmpty ?? true);

  /// True when the response carried at least one useful field.
  bool get hasAnything =>
      translation != null ||
      phonetic != null ||
      partOfSpeech != null ||
      gender != null ||
      definition != null ||
      examples.isNotEmpty ||
      alternates.isNotEmpty;

  AiWordDetails copyWith({bool? fromCache, DateTime? cachedAt}) {
    return AiWordDetails(
      word: word,
      source: source,
      target: target,
      translation: translation,
      phonetic: phonetic,
      partOfSpeech: partOfSpeech,
      gender: gender,
      definition: definition,
      examples: examples,
      alternates: alternates,
      fromCache: fromCache ?? this.fromCache,
      cachedAt: cachedAt ?? this.cachedAt,
    );
  }

  // ---------------------------------------------------------------------------
  // Serialisation (used by the persistent AI cache)
  // ---------------------------------------------------------------------------

  Map<String, dynamic> toJson() => {
        'word': word,
        'source': source,
        'target': target,
        'translation': translation,
        'phonetic': phonetic,
        'part_of_speech': partOfSpeech,
        'gender': gender,
        'definition': definition,
        'examples': [for (final e in examples) e.toJson()],
        'alternates': alternates,
        'from_cache': fromCache,
        'cached_at': cachedAt?.toIso8601String(),
      };

  factory AiWordDetails.fromJson(Map<String, dynamic> json) {
    final cachedAtRaw = json['cached_at'] as String?;
    return AiWordDetails(
      word: json['word'] as String,
      source: json['source'] as String,
      target: json['target'] as String,
      translation: json['translation'] as String?,
      phonetic: json['phonetic'] as String?,
      partOfSpeech: json['part_of_speech'] as String?,
      gender: json['gender'] as String?,
      definition: json['definition'] as String?,
      examples: [
        for (final e in (json['examples'] as List<dynamic>? ?? const []))
          AiExample.fromJson(Map<String, dynamic>.from(e as Map)),
      ],
      alternates: [
        for (final a in (json['alternates'] as List<dynamic>? ?? const []))
          a as String,
      ],
      fromCache: json['from_cache'] as bool? ?? false,
      cachedAt: cachedAtRaw == null ? null : DateTime.tryParse(cachedAtRaw),
    );
  }
}
